version: '3'
services:
  db:
     image: mysql:5.7
     volumes:
       - ./tmp/db:/var/lib/mysql
     restart: always
     logging:
       driver: none 
     environment:
       MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
       MYSQL_DATABASE: "${DB_NAME}"
       MYSQL_USER: "${DB_USER}"
       MYSQL_PASSWORD: "${DB_PASSWORD}"
  
  phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     logging:
       driver: none
     links:
       - db:mysql
     ports:
       - 8282:80
     environment:
       MYSQL_USERNAME: "${DB_USER}"
       MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

  web:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - app
    volumes:
      - .:/myapp
      - ./nginx:/etc/nginx/conf.d

  app:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/test
